### PR TITLE
Update ansible service  broker versions

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

I had experienced problems with ansible broker when using version provided by install script. 
It looks like team fixed couple issues and recent release version has change done by @matzew 
https://github.com/openshift/ansible-service-broker/pull/601

See tags: https://hub.docker.com/r/ansibleplaybookbundle/origin-ansible-service-broker/tags/

I have been using this today and it seems to work. I might miss some details about this so feel free to close this PR. Sharing this for wider group as this may help you guys to resolve problems with push (when you use latest abp). 

ping @pb82 @maleck13 @matzew @aidenkeating

### CODE REVIEW

**Comment by wtrocki** [comment]
Actually this will require much more testing. For the moment when installing fresh cluster mobile services are missing

**Comment by maleck13** [comment]
@wtrocki worth looking at the service broker logs it parses the apbs at startup, if they are not showing and the broker is starting up ok, it is likely these logs will give you the detail needed.
You can find the broker under the ansible-service-broker namespace. You will need admin perms to see it
```
oc login 
admin
admin

oc login -u system:admin

oc adm policy add-cluster-role-to-user admin admin
```
this will let you login with a new user called admin that will let you poke around in the UI

**Comment by wtrocki** [comment]
@maleck13 yes. Seen that yesterday. 
Problem is that template changed and it require little bit more than previous version. I think it's worth to update it and stay recent or at least test if it works. WDYT?

**Comment by pb82** [comment]
@wtrocki i just tried the `sprint-142` version and also adding the local config manually (https://github.com/openshift/ansible-service-broker/pull/601/files#diff-54e88cebcb04cc49b8796b2f774cb6c7). It doesn't seem to fix the problem where apbs don't appear after push.

**Comment by maleck13** [comment]
@wtrocki yes definitely worth staying upto date

**Comment by wtrocki** [comment]
When testing I see error:
```
[2018-01-05T16:20:10.557Z] [DEBUG] - calling NewSecureServingOptions
--
  | [2018-01-05T16:20:10.969Z] [DEBUG] - Creating k8s apiserver
  | [2018-01-05T16:20:10.97Z] [ERROR] - Unable to retrieve cluster roles rules from cluster
```

**Comment by wtrocki** [comment]
Problem resolved by @pb82 
Verified locally. It works like dream on mac platform.

Linux verification required.

**Comment by maleck13** [comment]
@pb82 @wtrocki there is a fix merged to master for the need to set ```auto_escalate``` to true so we should update asap. For now I think it is fine, but I don't think we would want to keep this setting long term as it will mean we are diverging from what I expect would be the standard/recommended set up

**Pull request merged**
