### PR TITLE
remove a question from the setup

### PR DESCRIPTION
**Pull request by wei-lee**
## Description

Remove the unused property "cluster_local_instance"

ping @johnfriz

### CODE REVIEW

**Comment by maleck13** [comment]
@wei-lee @johnfriz We already have this in progress https://github.com/aerogear/mobile-core/pull/120

**Comment by wei-lee** [comment]
@maleck13 LOL

**Comment by wei-lee** [comment]
@maleck13 Can we use this one as it also remove the unused "local:" part in "Cluster IP (Defaults to ${ipDefault})"

**Comment by maleck13** [comment]
sure if you are verifying it then we can close the other one

**Comment by wei-lee** [comment]
@maleck13 Yes, John has verified it (by watching me running the script 😄 )

**Comment by maleck13** [comment]
Did you check it on Fedora too?

**Comment by wei-lee** [comment]
@maleck13 No I didn't. Is PR #120 checked on Fedora? If so then I think it's ok because this PR is the same as #120, it just remove a few more words from one of the other question.

**Comment by maleck13** [comment]
I believe vitalli checked it and Phil is using Fedora so should be good

**Pull request merged**
