### PR TITLE
📝 Add steps for setting up a docker automated build

### PR DESCRIPTION
**Pull request by david-martin**
Steps were used to setup https://hub.docker.com/r/aerogearcatalog/metrics-apb/

### CODE REVIEW

**Comment by darahayes** [comment]
LGTM

@wtrocki suggested in the #aerogear IRC using a CI service to run the builds and push them to docker hub. That way we could get feedback in Github, and the builds would be publicly accessible. I'm going to spend some time researching this and I'll do up a little proposal.

How does that sound @david-martin ?

**Comment by david-martin** [comment]
Thanks @jasonmadigan.
@darahayes Getting feedback earlier would be good.
That would play into this jira https://issues.jboss.org/browse/AEROGEAR-1795 (cc @psturc)

**Comment by wtrocki** [comment]
@darahayes Automated builds are done for master branch merge. 
If we want to test PR's then we could have separate job to do it.

**Comment by psturc** [comment]
I would create a separate JIRA for that. The one above is just about implementing test playbook so the dev could check locally by running `apb test` that the app gets provisioned fine and some simple sanity checks passed.
Later we could use this for PR based ci after https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/issues/190 gets fixed.

**Comment by wtrocki** [comment]
@psturc Fully agree. We can also collect requirements and details to that jira by sending email to aerogear list. This is typical engineering request/technical debt/community functionality.

WDYT?

**Comment by psturc** [comment]
@wtrocki sounds great!

**Pull request merged**
