### PR TITLE
AEROGEAR-7611 remove local setup and minishift

### PR DESCRIPTION
**Pull request by finp**
## Motivation
Remove walkthroughs where the doc is duplicate of docs.aerogear.or as requested by community.
https://trello.com/c/AZIId1Mg/43-remove-walkthroughs-from-mobile-core-docs-where-info-is-available-on-docsaerogearorg

## Description
Making small PRs to address this

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@finp 

Following the error faced. It happened in 50% of the times and it is tracked in the OCP. For further information see [here](https://github.com/aerogear/minishift-mobilecore-addon/issues/18).  When you face it just run the Jenkins again. 


````
TASK [oc-cluster-up : Cluster up] **********************************************

fatal: [localhost]: FAILED! => {"changed": false, "cmd": "oc cluster up --service-catalog=true --host-data-dir=/home/jenkins/JENKINS_ROOT/workspace/aerogear_mobile-core_PR-196-SDCFHALRALNTBNSBXON4XZI2U3DBQTKK2LFKTJFOSHL6FRLOSOWQ/ui/openshift-data --routing-suffix=10.8.250.7.nip.io --public-hostname=test-mobile-core --version=v3.9.0 --image=openshift/origin", "delta": "0:01:03.596541", "end": "2018-07-26 04:28:35.104227", "msg": "non-zero return code", "rc": 1, "start": "2018-07-26 04:27:31.507686", "stderr": "FAIL\n   Error: cannot register the template service broker\n   Caused By:\n     Error: cannot create objects from template openshift-infra/template-service-broker-registration\n     Caused By:\n       Error: unable to recognize servicecatalog.k8s.io/v1beta1, Kind=ClusterServiceBroker: no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker", "stderr_lines": ["FAIL", "   Error: cannot register the template service broker", "   Caused By:", "     Error: cannot create objects from template openshift-infra/template-service-broker-registration", "     Caused By:", "       Error: unable to recognize servicecatalog.k8s.io/v1beta1, Kind=ClusterServiceBroker: no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker"], "stdout": "Using nsenter mounter for OpenShift volumes\nUsing 127.0.0.1 as the server IP\nStarting OpenShift using openshift/origin:v3.9.0 ...\n-- Starting OpenShift container ... \n   Creating initial OpenShift configuration\n   Starting OpenShift using container 'origin'\n   Waiting for API server to start listening\n   OpenShift server started\n-- Adding default OAuthClient redirect URIs ... OK\n-- Installing registry ... \n   scc \"privileged\" added to: [\"system:serviceaccount:default:registry\"]\n-- Installing router ... OK\n-- Importing image streams ... OK\n-- Importing templates ... OK\n-- Importing internal templates ... OK\n-- Installing service catalog ... OK\n-- Installing template service broker ... OK\n-- Registering template service broker with service catalog ... ", "stdout_lines": ["Using nsenter mounter for OpenShift volumes", "Using 127.0.0.1 as the server IP", "Starting OpenShift using openshift/origin:v3.9.0 ...", "-- Starting OpenShift container ... ", "   Creating initial OpenShift configuration", "   Starting OpenShift using container 'origin'", "   Waiting for API server to start listening", "   OpenShift server started", "-- Adding default OAuthClient redirect URIs ... OK", "-- Installing registry ... ", "   scc \"privileged\" added to: [\"system:serviceaccount:default:registry\"]", "-- Installing router ... OK", "-- Importing image streams ... OK", "-- Importing templates ... OK", "-- Importing internal templates ... OK", "-- Installing service catalog ... OK", "-- Installing template service broker ... OK", "-- Registering template service broker with service catalog ... "]}

	to retry, use: --limit @/home/jenkins/JENKINS_ROOT/workspace/aerogear_mobile-core_PR-196-SDCFHALRALNTBNSBXON4XZI2U3DBQTKK2LFKTJFOSHL6FRLOSOWQ/installer/playbook.retry
````

**Comment by camilamacedo86** [comment]
@finp could you rebase with the master?

**Comment by finp** [comment]
messed up :(

**Comment by camilamacedo86** [comment]
Sure. :-)

**Pull request merged**
