### PR TITLE
fix(installer): Issue 205: Installer successfully terminates improperly when an error occurs in the Ansible script execution

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
Issue https://github.com/aerogear/mobile-core/issues/205
## What
Fix to get the result of the ansible scripts 

## Why
To show the properly msg when it fails and the process was not executed in debug mode

## How
* Checking if the ansible has failures
* Fixing the place to get the result of the correct process

## Verification Steps
* Run it in a Fedora without the lib `libselinux-python` installed 
* See if it will finish with the ERROR and the info to re-run it with the --debug param to get further information as follows. ( Ref scenario Issue https://github.com/aerogear/mobile-core/issues/140 )

screen shot 2018-08-19 at 19 28 42

OR

* Comment the `oc cluster up` validation into the install.sh script for don't check it (The code is [here](https://github.com/aerogear/mobile-core/blob/master/installer/install.sh#L310))
* Remove the registry configured in the docker

screen shot 2018-08-19 at 20 15 53

* Executed the installer then it will fail in the `oc cluster up` ansible step
* Check if the error message as faced in the image above will appear 

OR

Run the installer with ANY setup which will be not checked and will make the ansible script fails. 

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress

- [X] Finished task

## Additional Notes

This code implementation can be improved when we try to attend the RFE https://github.com/aerogear/mobile-core/issues/133

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @maleck13 and @david-martin,

Please, could you check this one?

**Comment by camilamacedo86** [comment]
Also, I need a hand here with the Jenkins. It is not working, it is shown "Queued
mobile-core-test is offline" and the PR has been not tested. 

screen shot 2018-08-20 at 07 42 42

**Comment by camilamacedo86** [comment]
@trepel really tks for the help here regards the Jenkins.

**Comment by camilamacedo86** [comment]
Hi @maleck13 and @david-martin folks, 

It is opened a while. Please, could you please help us here for we are able to merge this one? It will solve the main problem faced by the doc team and probably its users in the installation.

**Comment by david-martin** [comment]
@camilamacedo86 I'm out of the loop on this repo. 
@wtrocki would you be able to help out @camilamacedo86 on getting this merged?

**Comment by wtrocki** [comment]
@camilamacedo86 Really good change. Going to verify that later and help you merge it.

**Comment by camilamacedo86** [comment]
@wtrocki really thank you. You are amazing !!!

**Comment by wtrocki** [comment]
@camilamacedo86 Reviewed and verified. We talking here aproach to hide complexity, but it's nice that we have option to get all the details. Thank you so much for improving mobile-core!

**Pull request merged**
