### PR TITLE
 ✨ update to use the openshift 3.9. Also using aerogear openshift web

### PR DESCRIPTION
**Pull request by wei-lee**
console image

## Motivation

The mobile-core was still using the old version of openshift, and the MCP is not relevant anymore.

## Description

This PR uses the latest version of openshift (v3.9), and it also removes MCP and uses the openshift web console image instead.

## Progress

- [x] Finished task

### CODE REVIEW

**Comment by wei-lee** [comment]
@maleck13 I fixed the issues you were seeing. can you try again?

**Comment by psturc** [comment]
@wei-lee not sure if it was introduced in this PR, but installation of oc client v3.9 does not work: https://gist.github.com/psturc/652935248055467ed0c0ed4aabe07e10

**Comment by wtrocki** [comment]
First attempt failed on usual step
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/oc
Target /usr/local/bin/oc
already exists. You may want to remove it:
  rm '/usr/local/bin/oc'
```

After executing this everything worked. Continuing tests!

**Comment by wtrocki** [comment]
@wei-lee Works like dream with the first start! Awesome work!
I have tested that on mac environment with docker `17.09.0`

Going to continue testing metrics and push APB's to make sure that there are no problems with routing etc. 

ping @david-martin

**Comment by wei-lee** [comment]
going to merge this now and we can address some of the issues in separate PRs. cc @maleck13

**Pull request merged**
