### PR TITLE
Changing ASB version to 1.1

### PR DESCRIPTION
**Pull request by AdamSaleh**
## Motivation
We want to have more recent ASB, preferably the latest stable release.

## Description

Changing ASB version to release 1.1.

### CODE REVIEW

**Comment by david-martin** [comment]
@AdamSaleh In general, I'm in favour of this.
But I don't know the impact of this.
Is this expected to break anything (in which case we'll need to schedule fixing things)
Are our APBs compatible with this version?

Maybe these questions don't matter and it's something we need to do anyways (so we are using a stable version).

**Comment by maleck13** [comment]
@david-martin I think the APBs will work (really we only have metrics and keycloak to worry about) and I think it is pretty important we keep moving with ASB releases to ensure we are working against the latest versions. We will avoid large chunks of unexpected work this way. 
@AdamSaleh I will try this out in the morning

I will try the metrics and keycloak ABS also and report any problems

**Comment by AdamSaleh** [comment]
@david-martin later on, when bumping point-versions and especially when bumping major versions, we should take caution. But we should at least be running a stable release, so far we have been using snapshot from sprint 42, which sounds sub-optimal.

**Comment by maleck13** [comment]
@AdamSaleh all good going to merge

**Pull request merged**
