### PR TITLE
Enabling Hawkular's metrics for MEM/CPU

### PR DESCRIPTION
**Pull request by matzew**
## Motivation

Enable MEM/CPU stats

## Description
enables MEM/CPU via existing Openshift feature for Heapster

## Progress

- [x] Finished task

### CODE REVIEW

**Comment by pb82** [comment]
@matzew what services is this reporting on? All pods deployed in openshift?

**Comment by matzew** [comment]
yes - all pods, in Openshift

**Comment by matzew** [comment]
@pb82 here is what it will look like:

**Comment by david-martin** [comment]
Lets merge. If it becomes burdensome to local dev, we can change back or suggest disabling via property

**Pull request merged**
