### PR TITLE
remove loopback alias

### PR DESCRIPTION
**Pull request by philbrookes**
## Motivation
Remove unrequired loopback alias

### CODE REVIEW

**Comment by wei-lee** [comment]
@philbrookes I added the `if` statement to only create the lo0 interface if it is a private ip. I actually don't know if it's still required. I think @jasonmadigan has a better idea? I am happy to remove it anyway.

**Comment by maleck13** [comment]
👀

**Comment by jasonmadigan** [comment]
@wei-lee assume this came from how we used to do this in `fh-cup`? The main reason we added it was to prevent IP addresses shifting/moving when switching networks, but it's also useless for accessing OCP from mobile apps, so I'd guess removal makes sense.

**Comment by aidenkeating** [comment]
@jasonmadigan I think *some* of this stuff came from https://github.com/fusor/catasb, which was the basis for the very early "installer" when we basically just needed catasb with tweaks and a few extras. I think it's good to remove.

**Comment by maleck13** [comment]
tried this on external ip and local ip all good

**Comment by maleck13** [comment]
@philbrookes do we want to retag to 1.0.0-alpha

**Comment by philbrookes** [comment]
@maleck13 I've updated the tag now.

**Pull request merged**
