### PR TITLE
Adding support/roles to run all versions of Fedora

### PR DESCRIPTION
**Pull request by camilamacedo86**
## Motivation
* Support all Fedora versions
* Issues: https://github.com/aerogear/mobile-core/issues/140 and https://github.com/aerogear/mobile-core/issues/110 and https://github.com/aerogear/mobile-docs/issues/345
 
## Description
Some roles are not covering the newer Fedora versions.

## Progress

- [x] Finished task
- [] TODO

## Additional Notes

To test it is required to try to install in a Fedora 27 and/or 28.

### CODE REVIEW

**Comment by camilamacedo86** [comment]
@finp I think it a better approach we keep in the rules/here all versions as it is done for IOS then it did not be changed for each new release of a SO, and in the doc has what is supported or not. The script did not mean what RedHat support or not, it is defined in the docs then if the user tries to use the installer with an unsupported version may it works or not no matter, however,  redhat ensure that it should work in the X versions as the support team will suggest/recommend the version Y if the user find some issue.

Also, if we should not allow the installer in X version of SO it should be made in the checks process of the installer and a friendly message should be outputted then it will be stopped before it started to be installed actually and not in this place. 

 Is it something that makes sense? Could you check if the issue https://github.com/aerogear/mobile-core/issues/110 tracked by you no so long is faced with this PR?

**Comment by finp** [comment]
@camilamacedo86  I don't think I should approve this, @maleck13 or @david-martin  could you take a look?

**Comment by camilamacedo86** [comment]
Hi @finp, It is fine, however, I think we can just close the issue tracked by yourself when it is approved and merged. Hi, folks, @maleck13 and @david-martin could you give a hand here for we move forward with it?

**Comment by finp** [comment]
@camilamacedo86  already closed https://github.com/aerogear/mobile-core/issues/110, could not reproduce

**Comment by maleck13** [comment]
Not sure why we had this limitation perhaps others have a better idea @philbrookes @david-martin

**Comment by david-martin** [comment]
> Not sure why we had this limitation perhaps others have a better idea

I think all is fine unless there valid reasons to restrict.
If we have to restrict, lets make a note of the reasons why somewher

**Comment by camilamacedo86** [comment]
Hi @maleck13 @david-martin,

Thank you for the collab/review. IMHO it has some restriction it should not be done in the roles anyway.  It should be made in the checks process of the installer where a friendly message should be outputted and the process finished before it actually starts to be installed.

* If the restriction be in the rules the customer will not receive a message and it will just face issues as tracked in  https://github.com/aerogear/mobile-core/issues/140 and https://github.com/aerogear/mobile-core/issues/110
* For each new version is required to update the rules which show not be a good an idea at all
* The iOS SO did not have a restrictions at this point for example, then why have it for Fedora?  

I am looking for the final position and if possible the approval of this pr in order to close the issues tracked which are solved with this PR.

**Comment by pmacko1** [comment]
hi @camilamacedo86. Unfortunately, I've not been able to run it in fedora28 in virtual machine. I used your fork, FEDORA branch.

Checking OpenShift client tools version. Should be >= 3.9
✓  OpenShift Client Tools version check passed. 

Checking Openshift cluster
Running oc cluster up ...                                               \

Getting a Docker client ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Checking type of volume mount ...
Determining server IP ...
Checking if OpenShift is already running ...
Checking for supported Docker version (=>1.22) ...
Checking if insecured registry is configured properly in Docker ...
Checking if required ports are available ...
Checking if OpenShift client is configured properly ...
Checking if image openshift/origin-control-plane:v3.10 is available ...
Starting OpenShift using openshift/origin-control-plane:v3.10 ...
I0808 13:22:32.431683    5182 flags.go:30] Running "create-kubelet-flags"
Error: error creating node config: could not run "create-kubelet-flags": Docker run error rc=139; caused by: Docker run error rc=139
Error to run 'oc cluster up'. 
See https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#getting-started.

**Comment by pmacko1** [comment]
@camilamacedo86 Unfortunately, this already exploded into 3 issues, i hope it will not grow further
https://github.com/aerogear/mobile-core/issues/200
https://github.com/aerogear/mobile-docs/issues/345

**Comment by camilamacedo86** [comment]
Hi @maleck13 and @david-martin,

It is opened for 23 days. Please, could you check it?

**Comment by camilamacedo86** [comment]
@pmacko1 as described in the error and our chat. The root cause of your problem is your cluster setup and not the mobile-core and its PR. Please, let focus on your issue in the proper place.

**Comment by camilamacedo86** [comment]
@david-martin thank you. I am rebasing it with the master and I already did a test locally all shows still working fine. It is a really small change. 

I will try to work on to help @pmacko1 in my free time regards the Fedora 28. I downloading the VM already.

**Pull request merged**
