### PR TITLE
Add doc around using self signed certs on mobile clients

### PR DESCRIPTION
**Pull request by PhilipGough**
Instructions for reading the openshift cluster cert and installing on client

### CODE REVIEW

**Comment by maleck13** [comment]
Wondering what is the best way to try this out. I ran the command and got the ca, we may need the the doc @vchepeli is working on to allow you to talk to the local openshift

**Comment by maleck13** [comment]
ping @finp should this go somewhere in mobile docs

**Comment by finp** [comment]
@PhilipGough  contact @pb82  about getting this info in the right place

**Comment by wei-lee** [comment]
@maleck13 I have asked @rachael-oregan to take a look and try it on real devices.

**Comment by vchepeli** [comment]
@PhilipGough rebase and resolve conflicts. AMI and has specific version of docker pip@10.0.1;ansible@2.5.4;docker@d17.09.1-ce;oc@v3.9.0+191fece;node@v6.14.3

**Comment by finp** [comment]
@maleck13  Given that we've now moved all user facing docs to mobile-docs repo, I'd suggest merging this (or not as suits you) and submitting it for tech writing review at mobile-docs.

**Comment by rachael-oregan** [comment]
Unfortunately I couldn't get mobile core running due to a `no disk space` issue I was having at `oc cluster up`

**Comment by pawelpaszki** [comment]
@rachael-oregan I was getting the same error with mobile core. I fixed it by installing version 17.09.1 of Docker

**Comment by aidenkeating** [comment]
@PhilipGough Tried this out on a device with Android, following the steps provided. Before trusting the cert metrics won't send because of a bad request, after it's trusted they will. Going to do the same on iOS now.

**Pull request merged**
