### PR TITLE
Fix dependency temporarily

### PR DESCRIPTION
**Pull request by aidenkeating**
Basically a release of this change (https://github.com/andrewrothstein/ansible-openshift-origin-client-tools/pull/10), to be used before the issue is resolved properly.

@johnfriz Mind taking a look?

### CODE REVIEW

**Comment by johnfriz** [comment]
@aidenkeating - worked perfectly for me. Cheers :-)

**Comment by maleck13** [comment]
@aidenkeating you have do not merge on this? Should we go ahead and merge if it solves the issue?

**Comment by aidenkeating** [comment]
@maleck13 Yep, I was hoping this would have been resolved by this morning without having to use a fork, but it's not so let's merge.

**Comment by jasonmadigan** [comment]
@aidenkeating @maleck13 

Getting this error still (master & 1.0.0 tag of mobile-core):

```
 [WARNING]: - andrewrothstein.alpine_glibc_shim was NOT installed successfully: - sorry, andrewrothstein.alpine_glibc_shim was not
found on https://galaxy.ansible.com.
```

**Pull request merged**
