### PR TITLE
remove unused cluster_local_instance param

### PR DESCRIPTION
**Pull request by philbrookes**
## Motivation
remove unused cluster_local_instance param

### CODE REVIEW

**Comment by philbrookes** [comment]
I think this fail is related to that mail thread that was going around this morning, I've rebased on Aiden's PR now.

**Comment by philbrookes** [comment]
@maleck13 this is passing now.

**Comment by maleck13** [comment]
@vchepeli can you try this out with Phil. Testing the different scenarios IE using the 192 local address and using the wifi network address

**Comment by vchepeli** [comment]
@philbrookes LGTM, now it makes sense to remove it from installer script

**Comment by philbrookes** [comment]
@vchepeli yes, I had taken that out, but had to restore it for the Jenkins tests to pass. I guess there is something in Jenkins that cares about that param.

Are you still happy for this to be merged?

**Comment by maleck13** [comment]
closing in favour of https://github.com/aerogear/mobile-core/pull/121

**Pull request closed without merging**
